### ISSUE TITLE
cannot import name Linear

### ISSUE THREAD

**Issue by yqjaoshuang** [dawnranger/IDEC-pytorch#1]
Hi~ Thanks a lot for sharing IDEC-pytorch codes.
There is an ImportError: cannot import name Linear.
Traceback (most recent call last):
  File "idec.py", line 21, in <module>
    from utils import MnistDataset, cluster_acc, Linear

Could you help to add the Linear codes? Thanks in advance.

**Comment by AshStuff** [comment]
you can just use `from torch.nn import Linear` in utils.py
